// <auto-generated />
using System;
using LiftTrackerApi.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiftTrackerApi.Migrations
{
    [DbContext(typeof(LiftTrackerDbContext))]
    [Migration("20250620000519_LoadOriginalSchemaDump")]
    partial class LoadOriginalSchemaDump
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LiftTrackerApi.Entities.Exercise", b =>
                {
                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.Migration", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<int>("Batch")
                        .HasColumnType("int")
                        .HasColumnName("batch");

                    b.Property<string>("Migration1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("migration");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("migrations", (string)null);
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.PasswordReset", b =>
                {
                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.HasIndex(new[] { "Email" }, "password_resets_email_index");

                    b.ToTable("password_resets", (string)null);
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.RoutineExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfSets")
                        .HasColumnType("int")
                        .HasColumnName("numberOfSets");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int?>("RestPeriod")
                        .HasColumnType("int")
                        .HasColumnName("restPeriod");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("WarmUp")
                        .HasColumnType("int")
                        .HasColumnName("warmUp");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("weight");

                    b.Property<int?>("WorkoutProgramRoutineId")
                        .HasColumnType("int")
                        .HasColumnName("workoutProgramRoutineId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "WorkoutProgramRoutineId" }, "RoutineExercises_ibfk_1");

                    b.HasIndex(new[] { "Uuid" }, "idx_uuid")
                        .IsUnique();

                    b.ToTable("RoutineExercises");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionExercise", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("char(100)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<uint?>("PlannedRestPeriodDuration")
                        .HasColumnType("int unsigned")
                        .HasColumnName("plannedRestPeriodDuration");

                    b.Property<int?>("PlannedWarmUp")
                        .HasColumnType("int")
                        .HasColumnName("plannedWarmUp");

                    b.Property<decimal?>("PlannedWeight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("plannedWeight");

                    b.Property<uint>("Position")
                        .HasColumnType("int unsigned")
                        .HasColumnName("position");

                    b.Property<uint?>("RoutineExerciseId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("routineExerciseId");

                    b.Property<bool>("Skipped")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("skipped");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<uint?>("WarmUpDuration")
                        .HasColumnType("int unsigned")
                        .HasColumnName("warmUpDuration");

                    b.Property<DateTime?>("WarmUpEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpEndedAt");

                    b.Property<DateTime?>("WarmUpStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpStartedAt");

                    b.Property<uint>("WorkoutSessionId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("workoutSessionId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoutineExerciseId" }, "sessionexercises_routineexerciseid_index");

                    b.HasIndex(new[] { "Uuid" }, "sessionexercises_uuid_index");

                    b.HasIndex(new[] { "WorkoutSessionId" }, "sessionexercises_workoutsessionid_foreign");

                    b.ToTable("SessionExercises");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionSet", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("endedAt");

                    b.Property<uint>("Position")
                        .HasColumnType("int unsigned")
                        .HasColumnName("position");

                    b.Property<decimal?>("Reps")
                        .HasColumnType("decimal(6,2) unsigned")
                        .HasColumnName("reps");

                    b.Property<uint?>("RestPeriodDuration")
                        .HasColumnType("int unsigned")
                        .HasColumnName("restPeriodDuration");

                    b.Property<DateTime?>("RestPeriodEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("restPeriodEndedAt");

                    b.Property<DateTime?>("RestPeriodStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("restPeriodStartedAt");

                    b.Property<uint>("SessionExerciseId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("sessionExerciseId");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("startedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<uint?>("WarmUpDuration")
                        .HasColumnType("int unsigned")
                        .HasColumnName("warmUpDuration");

                    b.Property<DateTime?>("WarmUpEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpEndedAt");

                    b.Property<DateTime?>("WarmUpStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpStartedAt");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SessionExerciseId" }, "sessionsets_sessionexerciseid_foreign");

                    b.HasIndex(new[] { "Uuid" }, "sessionsets_uuid_index");

                    b.ToTable("SessionSets");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("emailVerifiedAt");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("rememberToken");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "email_2")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Uuid" }, "idx_uuid")
                        .IsUnique()
                        .HasDatabaseName("idx_uuid1");

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgramRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NormalDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('any','Monday','Tuesday','Wensday','Thursday','Friday','Saturday','Sunday')")
                        .HasColumnName("normalDay")
                        .HasDefaultValueSql("'any'");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("WorkoutProgramId")
                        .HasColumnType("int")
                        .HasColumnName("workoutProgramId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "WorkoutProgramId" }, "WorkoutProgramRoutines_ibfk_1");

                    b.HasIndex(new[] { "Uuid" }, "idx_uuid")
                        .IsUnique()
                        .HasDatabaseName("idx_uuid2");

                    b.ToTable("WorkoutProgramRoutines");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutSession", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("id");

                    b.Property<decimal?>("BodyWeight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("bodyWeight");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("endedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("startedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<uint?>("UserId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("userId");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<uint?>("WorkoutProgramRoutineId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("workoutProgramRoutineId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedAt" }, "workoutsessions_createdat_index");

                    b.HasIndex(new[] { "UserId" }, "workoutsessions_userid_index");

                    b.HasIndex(new[] { "Uuid" }, "workoutsessions_uuid_index");

                    b.HasIndex(new[] { "WorkoutProgramRoutineId" }, "workoutsessions_workoutprogramroutineid_index");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.RoutineExercise", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.WorkoutProgramRoutine", "WorkoutProgramRoutine")
                        .WithMany("RoutineExercises")
                        .HasForeignKey("WorkoutProgramRoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("RoutineExercises_ibfk_1");

                    b.Navigation("WorkoutProgramRoutine");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionExercise", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("SessionExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sessionexercises_workoutsessionid_foreign");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionSet", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.SessionExercise", "SessionExercise")
                        .WithMany("SessionSets")
                        .HasForeignKey("SessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sessionsets_sessionexerciseid_foreign");

                    b.Navigation("SessionExercise");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgramRoutine", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutProgramRoutines")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("WorkoutProgramRoutines_ibfk_1");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionExercise", b =>
                {
                    b.Navigation("SessionSets");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgram", b =>
                {
                    b.Navigation("WorkoutProgramRoutines");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgramRoutine", b =>
                {
                    b.Navigation("RoutineExercises");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutSession", b =>
                {
                    b.Navigation("SessionExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
