// <auto-generated />
using System;
using LiftTrackerApi.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiftTrackerApi.Migrations
{
    [DbContext(typeof(LiftTrackerDbContext))]
    [Migration("20260418104526_AddRpeToRoutineAndSessionEntities")]
    partial class AddRpeToRoutineAndSessionEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LiftTrackerApi.Entities.RoutineExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfSets")
                        .HasColumnType("int")
                        .HasColumnName("numberOfSets");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int?>("RestPeriod")
                        .HasColumnType("int")
                        .HasColumnName("restPeriod");

                    b.Property<int?>("Rpe")
                        .HasColumnType("int")
                        .HasColumnName("rpe");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("WarmUp")
                        .HasColumnType("int")
                        .HasColumnName("warmUp");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("weight");

                    b.Property<int?>("WorkoutProgramRoutineId")
                        .HasColumnType("int")
                        .HasColumnName("workoutProgramRoutineId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "WorkoutProgramRoutineId" }, "RoutineExercises_ibfk_1");

                    b.HasIndex(new[] { "Uuid" }, "idx_uuid")
                        .IsUnique();

                    b.ToTable("RoutineExercises");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("char(100)")
                        .HasColumnName("name")
                        .IsFixedLength();

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("PlannedRestPeriodDuration")
                        .HasColumnType("int")
                        .HasColumnName("plannedRestPeriodDuration");

                    b.Property<int?>("PlannedRpe")
                        .HasColumnType("int")
                        .HasColumnName("plannedRpe");

                    b.Property<int?>("PlannedWarmUp")
                        .HasColumnType("int")
                        .HasColumnName("plannedWarmUp");

                    b.Property<decimal?>("PlannedWeight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("plannedWeight");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<int?>("RoutineExerciseId")
                        .HasColumnType("int");

                    b.Property<bool>("Skipped")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("skipped");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("WarmUpDuration")
                        .HasColumnType("int")
                        .HasColumnName("warmUpDuration");

                    b.Property<DateTime?>("WarmUpEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpEndedAt");

                    b.Property<DateTime?>("WarmUpStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpStartedAt");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("RoutineExerciseId")
                        .HasDatabaseName("sessionexercises_routineexerciseid_index");

                    b.HasIndex("WorkoutSessionId");

                    b.HasIndex("RoutineExerciseId", "CreatedAt")
                        .HasDatabaseName("sessionexercises_routineexerciseid_createdat_index");

                    b.HasIndex(new[] { "Uuid" }, "sessionexercises_uuid_index");

                    b.ToTable("SessionExercises");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("endedAt");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<decimal?>("Reps")
                        .HasColumnType("decimal(6,2) unsigned")
                        .HasColumnName("reps");

                    b.Property<int?>("RestPeriodDuration")
                        .HasColumnType("int")
                        .HasColumnName("restPeriodDuration");

                    b.Property<DateTime?>("RestPeriodEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("restPeriodEndedAt");

                    b.Property<DateTime?>("RestPeriodStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("restPeriodStartedAt");

                    b.Property<int?>("Rpe")
                        .HasColumnType("int")
                        .HasColumnName("rpe");

                    b.Property<int>("SessionExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("sessionExerciseId");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("startedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("WarmUpDuration")
                        .HasColumnType("int")
                        .HasColumnName("warmUpDuration");

                    b.Property<DateTime?>("WarmUpEndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpEndedAt");

                    b.Property<DateTime?>("WarmUpStartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("warmUpStartedAt");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SessionExerciseId" }, "sessionsets_sessionexerciseid_foreign");

                    b.HasIndex(new[] { "Uuid" }, "sessionsets_uuid_index");

                    b.ToTable("SessionSets");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Uuid" }, "idx_uuid")
                        .IsUnique()
                        .HasDatabaseName("idx_uuid1");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Uuid" }, "idx_uuid")
                        .IsUnique()
                        .HasDatabaseName("idx_uuid2");

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgramRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NormalDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('any','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')")
                        .HasColumnName("normalDay")
                        .HasDefaultValueSql("'any'");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("WorkoutProgramId")
                        .HasColumnType("int")
                        .HasColumnName("workoutProgramId");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "WorkoutProgramId" }, "WorkoutProgramRoutines_ibfk_1");

                    b.HasIndex(new[] { "Uuid" }, "idx_uuid")
                        .IsUnique()
                        .HasDatabaseName("idx_uuid3");

                    b.ToTable("WorkoutProgramRoutines");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("BodyWeight")
                        .HasPrecision(6)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("bodyWeight");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("deletedAt");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("endedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("startedAt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updatedAt");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<Guid?>("Uuid")
                        .HasColumnType("char(36)")
                        .HasColumnName("uuid");

                    b.Property<int?>("WorkoutProgramRoutineId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("WorkoutProgramRoutineId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("workoutsessions_userid_createdat_uuid_index");

                    b.HasIndex(new[] { "Uuid" }, "workoutsessions_uuid_index");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.RoutineExercise", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.WorkoutProgramRoutine", "WorkoutProgramRoutine")
                        .WithMany("RoutineExercises")
                        .HasForeignKey("WorkoutProgramRoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("RoutineExercises_ibfk_1");

                    b.Navigation("WorkoutProgramRoutine");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionExercise", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.RoutineExercise", "RoutineExercise")
                        .WithMany()
                        .HasForeignKey("RoutineExerciseId");

                    b.HasOne("LiftTrackerApi.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("SessionExercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sessionexercises_workoutsessionid_foreign");

                    b.Navigation("RoutineExercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionSet", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.SessionExercise", "SessionExercise")
                        .WithMany("SessionSets")
                        .HasForeignKey("SessionExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("sessionsets_sessionexerciseid_foreign");

                    b.Navigation("SessionExercise");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgramRoutine", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutProgramRoutines")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("WorkoutProgramRoutines_ibfk_1");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutSession", b =>
                {
                    b.HasOne("LiftTrackerApi.Entities.WorkoutProgramRoutine", "WorkoutProgramRoutine")
                        .WithMany()
                        .HasForeignKey("WorkoutProgramRoutineId");

                    b.Navigation("WorkoutProgramRoutine");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.SessionExercise", b =>
                {
                    b.Navigation("SessionSets");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgram", b =>
                {
                    b.Navigation("WorkoutProgramRoutines");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutProgramRoutine", b =>
                {
                    b.Navigation("RoutineExercises");
                });

            modelBuilder.Entity("LiftTrackerApi.Entities.WorkoutSession", b =>
                {
                    b.Navigation("SessionExercises");
                });
#pragma warning restore 612, 618
        }
    }
}
