image: node:22

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: "lift_tracker_api_test"
        MYSQL_RANDOM_ROOT_PASSWORD: "no"
        MYSQL_USER: "lift_tracker_api_test"
        MYSQL_PASSWORD: "lift_tracker_api_test"

pipelines:
  branches:
    master:
      - parallel:
          - step:
              name: Build, test, deploy frontend
              caches:
                - node
              script:
                - . ci/should-build-frontend.sh
                - echo 'Installing dependencies'
                - npm ci
                - echo 'Running linter'
                - npm run lint
                - echo 'Running tests'
                - npm test
                - echo 'Building'
                - node ci/replace-config.js
                - npm run prod
                - echo 'Starting deploy'
                - tar -czf artifacts-frontend.tar.gz -C dist .
                - pipe: atlassian/ssh-run:0.4.1
                  variables:
                    SSH_USER: $PROD_USER
                    SERVER: $PROD_IP
                    MODE: "command"
                    COMMAND: >
                      rm -rf /tmp/deploy-frontend
                      && mkdir /tmp/deploy-frontend
                - pipe: atlassian/scp-deploy:0.3.3
                  variables:
                    USER: $PROD_USER
                    SERVER: $PROD_IP

                    REMOTE_PATH: "/tmp/deploy-frontend"
                    LOCAL_PATH: "artifacts-frontend.tar.gz"
                    EXTRA_ARGS: [ "-r" ]
                - pipe: atlassian/ssh-run:0.4.1
                  variables:
                    SSH_USER: $PROD_USER
                    SERVER: $PROD_IP
                    MODE: "command"
                    COMMAND: >
                      set -x
                      && rm -rf /var/www/html/lift-tracker/index.html
                      && rm -rf /var/www/html/lift-tracker/js
                      && tar -xf /tmp/deploy-frontend/artifacts-frontend.tar.gz -C /var/www/html/lift-tracker
                      && sudo systemctl reload nginx
                - echo 'Purging CDN cache'
                - >
                  curl \
                   -X POST "https://api.cloudflare.com/client/v4/zones/c1c95b982d4310a8f3ccd3b8483c6df7/purge_cache" \
                   -H "Authorization: Bearer $CLOUDFLARE_AUTH_TOKEN" \
                   -H "Content-Type:application/json" \
                   --data '{"purge_everything":true}'
          - step:
              name: Build, test, dotnet api
              image: mcr.microsoft.com/dotnet/sdk:9.0
              caches:
                - dotnetcore
              script:
                - . ci/should-build-api.sh
                - cd LiftTrackerApi
                - echo 'Installing dependencies'
                - apt-get update && apt-get install -y gettext # for envsubst
                - dotnet tool restore
                - echo 'Checking formatting'
                - dotnet csharpier check . && dotnet csharpier check ../LiftTrackerApi.Tests
                - echo 'Migrating test database'
                - ASPNETCORE_ENVIRONMENT=Test dotnet ef database update
                - echo 'Running tests'
                - dotnet test
                - echo 'Publishing solution'
                - envsubst < appsettings.Production.template.json > appsettings.Production.json
                - dotnet publish LiftTrackerApi.csproj -c Release -r linux-x64 --self-contained true -o ./publish
                - echo 'Starting deploy';
                - tar -czf artifacts-backend.tar.gz ./publish;
                - pipe: atlassian/ssh-run:0.4.1
                  variables:
                    SSH_USER: $PROD_USER
                    SERVER: $PROD_IP
                    MODE: "command"
                    COMMAND: >
                      rm -rf /tmp/deploy-backend/
                      && mkdir /tmp/deploy-backend/
                - pipe: atlassian/scp-deploy:0.3.3
                  variables:
                    USER: $PROD_USER
                    SERVER: $PROD_IP
                    REMOTE_PATH: "/tmp/deploy-backend"
                    LOCAL_PATH: "artifacts-backend.tar.gz"
                    EXTRA_ARGS: [ "-r" ]
                - pipe: atlassian/ssh-run:0.4.1
                  variables:
                    SSH_USER: $PROD_USER
                    SERVER: $PROD_IP
                    MODE: "command"
                    COMMAND: >
                      set -x
                      && tar -xf /tmp/deploy-backend/artifacts-backend.tar.gz -C /var/www/html/lift-tracker
                      && sudo systemctl reload nginx
                      && sudo systemctl restart lt-api
              services:
                - mysql
      - step:
          name: Tagging successful build
          deployment: Cloudflare
          script:
            - git fetch origin "refs/notes/*:refs/notes/*" -f
            - git notes add -f -m 'ci-build-pass' && git push origin refs/notes/*

